spring.application.name=ChronoFlex
spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8080}
server.address=0.0.0.0

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Driver (optional but safe)
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

hf.api.token=${HF_TOKEN}
hf.model.url=${HF_MODEL_URL:https://router.huggingface.co/v1/chat/completions}
hf.model.name=${HF_MODEL_NAME}

turnstile.secret=${TURNSTILE_SECRET}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
